// THIS FILE IS AUTO GENERATED BY Kepler DO NOT EDIT!!
package endpoint

import (
	service "Go-001/Week04/homework/internal/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	GetUserNameEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.HomeworkService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{GetUserNameEndpoint: MakeGetUserNameEndpoint(s)}
	for _, m := range mdw["GetUserName"] {
		eps.GetUserNameEndpoint = m(eps.GetUserNameEndpoint)
	}
	return eps
}
