// THIS FILE IS AUTO GENERATED BY Kepler DO NOT EDIT!!
package server

import (
	service "Go-001/Week04/homework/internal/service"
	endpoint "github.com/go-kit/kit/endpoint"
)

func addDefaultServiceMiddleware(mw []service.Middleware) []service.Middleware {
	return append(mw, service.LoggingMiddleware())
}
func addEndpointMiddlewareToAllMethods(mw map[string][]endpoint.Middleware, m endpoint.Middleware) {
	methods := []string{"GetUserName"}
	for _, v := range methods {
		mw[v] = append(mw[v], m)
	}
}
