// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"Go-001/Week04/homework/internal/domain/user"
	"Go-001/Week04/homework/internal/domain/user/entity"
	"Go-001/Week04/homework/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHomeworkService(db *gorm.DB) service.HomeworkService {
	userEntity := entity.NewBasicUserEntity(db)
	userDomainService := user.NewBasicDomainService(userEntity)
	homeworkService := service.NewBasicHomeworkService(userDomainService)
	return homeworkService
}
